language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: true
node_js:
  - '8'
before_script:
  - npm install cypress hyperapp
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
