language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: true
node_js:
  - '8'
# install peer dependencies we need before installing
# main dependencies so all get cached
before_install:
  - npm install cypress hyperapp
script:
  # builds and tests everything
  - npm run build
  - travis_retry npm run test:ci -- --record
after_success:
  - npm run semantic-release || true
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
